---
# Kiwix
kiwix_version: kiwix-tools_linux-armhf-3.2.0-1
vikidia_version: vikidia_en_all_nopic_2021-03
wiktionary_version: wiktionary_en_simple_all_nopic_2022-0

# Moodle DB
mysql_root_password:

mysql_enabled_on_startup: true

mysql_databases:
  - name: moodle
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    replicate: 1

mysql_users:
  - name: elimu
    host: "localhost"
    password: elimu
    priv: "moodle.*:SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER"

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

# Moodle config

# The version of moodle to install.
moodle_version: 310

# A path where to save the data.
moodle_data_directory: /mnt/content/moodledata

# The permissions of the created directories.
moodle_directory_mode: "0750"

# Details to connect to the database.
moodle_database_type: mariadb
moodle_database_hostname: localhost
moodle_database_name: moodle
moodle_database_username: elimu
moodle_database_password: elimu
moodle_database_prefix: ""

moodle_httpd_data_directory: /var
moodle_httpd_owner: www-data
moodle_httpd_group: www-data
moodle_directory_mode: "0777"

# The URL where to serve content.
moodle_wwwroot: "http://moodle.local"

