---
# Elimupi release version
elimupi_release: 3.1.0

elimupi_release_file:  "/root/elimupi_release-{{ elimupi_release }}-{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}" 

system_locales:  
  - nl_NL.UTF-8
  - en_GB.UTF-8
  - sw_KE
  - sw_TZ
  - am_ET

software_packages:
  - ufw
  - git
  - nginx
  - php
  - php-fpm
  - php-curl
  - php-xml
  - php-mbstring
  - php-zip
  - php-gd
  - php-intl
  - php-xmlrpc
  - php-soap
  - php-mysql
  - php-ldap
  - iptables
  - libffi-dev
  - python3-pip
  - python3-pkg-resources
  - dirmngr
  - dnsmasq
  - fdroidserver
  - ntfs-3g
  - hostapd
  - udhcpd

# OpenLDAP
openldap_server_domain: elimupi.local

# This is the password for admin for openldap
openldap_server_rootpw: "{{ elimupi_ldap_password }}" 
# Root dn
openldap_server_rootdn: cn=Manager,{{ _basedn }}

openldap_server_app_path: "/etc/ldap/"
openldap_server_user: "openldap"

# SSL-related stuff
openldap_server_enable_tls: false
openldap_server_ssl_cert: "{{ openldap_sever_app_path }}/certs/cert.crt"
openldap_server_ssl_key: "{{ openldap_server_app_path }}/certs/my.key"

# Use self-signed certificate
openldap_server_generate_cert: false
# The self signed ssl parameters
openldap_server_ssl:
  country: CZ
  state: Central Bohemia
  location: Prague
  organization: m-cloud.cz

# ACLs - Do not touch unless you know what you're doing
openldap_olcAccess:
  - >-
    to attrs=userPassword,shadowLastChange
    by self write
    by anonymous auth
    by * none
  - >-
    to dn.subtree="{{ _basedn }}"
    by dn.exact="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" manage
    by * read
# internal basedn variable
_basedn: "dc={{ openldap_server_domain.split('.')[0] }},dc={{ openldap_server_domain.split('.')[1] }}"



# Kiwix
#
# A path where to save the data.
kiwix_data_directory: /mnt/content/wiki
kiwix_directory_mode: "0755"

kiwix_version: kiwix-tools_linux-armhf-3.2.0-1
vikidia_version: vikidia_en_all_nopic_2021-03
wiktionary_version: wiktionary_en_simple_all_nopic_2022-09

ansible_host_key_checking: false

# Moodle DB
mysql_root_password:

mysql_enabled_on_startup: true

mysql_databases:
  - name: moodle
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    replicate: 1

mysql_users:
  - name: elimu
    host: "localhost"
    password: elimu
    priv: "moodle.*:SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER"

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python3-mysqldb

# Moodle config

moodle_data_directory: /var/moodledata


# The permissions of the created directories.
moodle_directory_mode: "0750"

# Details to connect to the database.
moodle_database_hostname: localhost
moodle_database_username: elimu
moodle_database_prefix: ""

moodle_httpd_data_directory: /var
moodle_httpd_owner: www-data
moodle_httpd_group: www-data

moodle_root_path: /var/moodle
moodle_dataroot_path: /var/moodledata

moodle_version: '4.00'

moodle_root_user: root
moodle_root_group: root
moodle_root_permissions: '0755'

moodle_dataroot_user: www-data
moodle_dataroot_group: www-data
moodle_dataroot_permissions: '0777'

moodle_fullname: DEAN Moodle
moodle_shortname: deanmoodle

moodle_wwwroot: "http://moodle.elimupi.online"

moodle_database_type: mariadb

moodle_database_name: moodle
moodle_database_user: elimu
moodle_database_password: elimu

moodle_database_host: 'localhost'
moodle_database_port: '3306'

moodle_admin_username: admin
moodle_admin_password: elimupi
moodle_admin_email: admin@elimup.online

moodle_enable_debug: false

# Kolibri config
# The databases and storage 

kolibri_install: True
kolibri_enabled: True

# Kolibri folder to store its data and configuration files.
#kolibri_home: "{{ content_base }}/kolibri"
kolibri_home: "/mnt/content/kolibri-home"

kolibri_http_port: 8080
kolibri_url: /kolibri/
kolibri_path: "{{ iiab_base }}/kolibri"
kolibri_exec_path: /usr/bin/kolibri 

# Kolibri system user
#kolibri_user: kolibri
kolibri_user: pi

# Kolibri setup will be provisioned with default administration account, preset and
# language. You could turn this to 'False' while reinstalling kolibri.
kolibri_provision: False 

# Kolibri Facility name
kolibri_facility: 'DEAN - Elimupi'

# Kolibri Preset type: formal, nonformal, informal
kolibri_preset: 'formal'

# Kolibri default language (ar,bn-bd,en,es-es,fa,fr-fr,hi-in,mr,nyn,pt-br,sw-tz,ta,te,ur-pk,yo,zu)
kolibri_language: 'en'

# Kolibri admin account
kolibri_admin_user: 'admin'
kolibri_admin_password: ''
