---
- name: Copy default config
  template:
    src: slapd.j2
    dest: /etc/default/slapd
    mode: 0755
  notify: restart slapd

- name: Make sure slapd is enabled and running
  systemd:
    name: slapd
    state: started
    enabled: true

- name: Configure basedn as default suffix
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcSuffix: "{{ _basedn }}"
    state: exact

- name: Set up a root user
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcRootDN: "{{ openldap_server_rootdn }}"
      olcRootPW: "{{ openldap_server_rootpw }}"
    state: exact

- name: Set up the ACL
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcAccess: "{{ openldap_olcAccess }}"
    ordered: true
    state: exact

- name: Generate basedn
  community.general.ldap_entry:
    dn: "{{ _basedn }}"
    objectClass: domain

- name: Load encryption config
  community.general.ldap_attrs:
    dn: cn=config
    attributes:
      olcTLSCertificateKeyFile: "{{ openldap_server_ssl_key }}"
      olcTLSCertificateFile: "{{ openldap_server_ssl_cert }}"
    state: exact
  when: openldap_server_enable_tls
  notify: restart slapd
