---
- name: Create the directory for ldap certificates
  file:
    path: "{{ openldap_server_app_path }}/certs/"
    state: directory
    mode: 0700
    owner: "{{ openldap_server_user }}"
    group: "{{ openldap_server_user }}"

- name: Generate the private key for certificate request
  command: openssl genrsa -des3 -passout pass:password -out my1.key 1024
  args:
    chdir: "{{ openldap_server_app_path }}/certs/"
    creates: "{{ openldap_server_app_path }}/certs/my1.key"
  become: true
  become_user: "{{ openldap_server_user }}"

- name: Strip the passphrase from the key
  command: openssl rsa -in my1.key -passin pass:password -out my.key
  args:
    chdir: "{{ openldap_server_app_path }}/certs/"
    creates: "{{ openldap_server_app_path }}/certs/my.key"
  become: true
  become_user: "{{ openldap_server_user }}"

- name: Create and sign the the new certificate
  command: "openssl req -new -x509 -subj
    '/C={{ openldap_server_ssl.country }}\
    /ST={{ openldap_server_ssl.state }}\
    /L={{ openldap_server_ssl.location }}\
    /O={{ openldap_server_ssl.organization }}\
    /CN={{ ansible_hostname }}/'
    -days 3650 -key my.key -out cert.crt -extensions v3_ca"
  args:
    chdir: "{{ openldap_server_app_path }}/certs/"
    creates: "{{ openldap_server_app_path }}/certs/cert.crt"
  become: true
  become_user: "{{ openldap_server_user }}"
