---
- name: Install ldap
  include_tasks: install_ldap.yml

- name: Generate self-signed certs if required
  include_tasks: generate_cert.yml
  when: openldap_server_generate_cert

- name: Configure ldap
  include_tasks: configure_ldap.yml
