- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 16.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x bionic main
    update_cache: yes

- name: "Install nodejs and other dependencies"
  apt:
    update_cache: yes
    name:
      - nodejs
      - jq
      - ffmpeg
      - npm
    state: present

- name: "Clone Scratch GUI repository"
  git:
    repo: "https://github.com/LLK/scratch-gui.git"
    dest: "/opt/scratch-gui"
    force: true

- name: "Install Scratch GUI dependencies"
  npm:
    path: "/opt/scratch-gui"
    state: present

- name: "Build Scratch GUI"
  command: npm install
  args:
    chdir: "/opt/scratch-gui"

- name: "Copy Scratch GUI service file"
  ansible.builtin.template:
    src: "scratch-gui.service.j2"
    dest: "/etc/systemd/system/scratch-gui.service"
    mode: "0755"

- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

- name: Enable and start scratch-gui service
  systemd:
    name: scratch-gui
    state: started
    enabled: yes

- name: Set scratch.local
  ansible.builtin.copy:
    src: "nginx/scratch.local"
    dest: /etc/nginx/sites-available/scratch.local
  notify:
    - Restart Nginx

- name: Enable scratch nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/scratch.local
    dest: /etc/nginx/sites-enabled/scratch.local
    owner: root
    group: root
    state: link
  notify:
    - Restart Nginx

- name: Copy tutorial videos list
  ansible.builtin.copy:
    src: "roles/common/files/scratch_gui/videos.json"
    dest: /tmp/

- name: Download all the Tutorial Videos, this can take a while...
  ansible.builtin.script: roles/common/files/scratch_gui/download_tutorial_videos.sh /tmp/videos.json
  args:
    creates: /tmp/videos_downloaded

- name: Path Scratch GUI to play the tutorial videos from local
  ansible.builtin.copy:
    src: "roles/common/files/scratch_gui/cards.jsx"
    dest: /opt/scratch-gui/src/components/cards/cards.jsx

- name: Add support for scratch-storage chunk files in webpack configuration
  ansible.builtin.copy:
    src: "roles/common/files/scratch_gui/webpack.config.js"
    dest: /opt/scratch-gui/webpack.config.js