---
- name: Configure dnsmasq 
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
