# Install_kolibri

# install Kolibri install support python libraries -> moved to ospackages.yml
#apt install libffi-dev python3-pip python3-pkg-resources dirmngr -y

# install pip3 packages
- name: Install multi python packages with version specifiers
  pip:
    name:
      - pip
      - setuptools
      - cffi
    executable: pip3
    
# Add http://ppa.launchpad.net/learningequality as installer source -> moved to ospackages.yml
# Add apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81 -> moved to ospackages.yml

- name: Run "apt-get update"
  apt:
    update_cache: yes

#Install Kolibri components
- name: Install applications
  apt:
    name:
    - kolibri
    - kolibri-server