---
# Main flow of the Ansible tasks



# kiwix - install kiwix
- include_tasks: kiwix.yml

# moodle - install moodle
- include_tasks: moodle.yml

# ldap - install openldap 
- include_tasks: ldap.yml

# firewall - setup firewall
- include_tasks: firewall.yml

# offline_redirection - setup offline redirections
- include_tasks: offline_redirection.yml

# release file 
- include_tasks: release.yml
