---
# Main flow of the Ansible tasks

# setup - basic setup
- name: Include setup tasks
  include_tasks: setup.yml

# ospackages - install OS packages
- include_tasks: packages.yml

# setup wifi
- include_tasks: wifi.yml

# webserver - install webserver
- include_tasks: webserver.yml

# webserver - install offline coding systems
- include_tasks: coding_systems.yml

# X Server
- include_tasks: desktop.yml

# fdroid - install fdroid
- include_tasks: fdroid.yml

# kolibri - install kolibri
- include_tasks: kolibri.yml

# kiwix - install kiwix
- include_tasks: kiwix.yml

# moodle - install moodle
- include_tasks: moodle.yml

# ldap - install openldap
- include_tasks: ldap.yml

# offline_redirection - setup offline redirections
- include_tasks: offline_redirection.yml

# install OpenVPN
- include_tasks: openvpn.yml

# configure OneDrive
- include_tasks: onedrive.yml

# install Squid proxy
- include_tasks: proxy.yml

#SETUP DEAN SCRIPT
- include_tasks: ddnsclient.yml

# release file
- include_tasks: release.yml

# firewall - setup firewall
- include_tasks: iptables.yml

# leaphy - install leaphy easybloqs
- include_tasks: leaphy.yml

# reboot
- include_tasks: reboot.yml
