- name: Include setup.yml
  include: setup.yaml

- name: Include users.yml
  include: users.yaml

- name: Include packages.yml
  include: packages.yaml

# - name: Include firewall.yml
#   include: firewall.yaml

