---
# Main flow of the Ansible tasks
# setup - basic setup
- name: Include setup tasks
  include_tasks: setup.yml

# users - add users and groups
- name: Include accounts tasks
  include_tasks: accounts.yml

# ospackages - install OS packages
- include_tasks: packages.yml

# git clone
- include_tasks: repo.yml

# firewall - setup firewall
#   include: firewall.yaml

# network - setup network wifi
#- include_tasks: network.yml

# webserver - install webserver
- include_tasks: webserver.yml

# fdroid - install fdroid
- include_tasks: fdroid.yml

# kolibri - install kolibri
- include_tasks: kolibri.yml

# kiwix - install kiwix
- include_tasks: kiwix.yml

# moodle - install moodle
- include_tasks: moodle.yml
