---
- name: Create and configure moodle database
  include_role:
    name: geerlingguy.mysql

- name: Create directory /var/moodlecontent
  ansible.builtin.file:
    path: /var/moodlecontent
    state: directory
    mode: '0755'

- name: Create directory /var/moodlesql
  ansible.builtin.file:
    path: /var/moodlesql
    state: directory
    mode: '0755'

- name: Clone moodle
  ansible.builtin.git:
    repo: "{{ moodle_repo_url }}"
    dest: "{{ moodle_root_path }}"
    version: "{{ moodle_version }}"
    force: yes
    depth: 1
    accept_hostkey: true
  become: true

- name: Gitconfig save /var/moodle
  shell: git config --global --add safe.directory "{{ moodle_root_path }}"
  become: true 

- name: Download moosh | Moodle Shell
  ansible.builtin.unarchive:
    src: "{{ moodle_shell_url_src }}"
    dest: /var
    remote_src: yes

- name: Moosh symbolic link
  ansible.builtin.file:
    src: /var/moosh/moosh.php
    dest: /usr/local/bin/moosh
    owner: root
    group: root
    state: link

- name: Change owner and persmissions of directory /var/moodle
  ansible.builtin.file:
    path: "{{ moodle_root_path }}" 
    state: directory
    owner: "{{ moodle_httpd_owner }}" 
    mode: '0755'
    recurse: yes

- name: Create moodle data directory
  ansible.builtin.file:
    path: "{{ moodle_data_directory }}"
    state: directory
    owner: "{{ moodle_httpd_owner }}"
    group: "{{ moodle_httpd_group }}"
    mode: "{{ moodle_directory_mode }}"

- name: Copy Moodle ldap configuration
  ansible.builtin.template:
    src: auth_ldap_config.xml.j2
    dest: /var/www/html/admin/files/auth_ldap_config.xml
    mode: "0755"

- name: Execute installation script
  become: yes
  become_user: "{{ moodle_httpd_owner }}"
  command: |
    /usr/bin/php admin/cli/install.php
    --wwwroot={{ moodle_wwwroot }}
    --dataroot={{ moodle_data_directory }}
    --dbtype=mariadb
    --dbhost=localhost
    --dbname={{ moodle_database_name }}
    --dbuser={{ moodle_database_username }}
    --dbpass={{ moodle_database_password }}
    --fullname="DEAN Moodle"
    --shortname=Moodle
    --summary=Moodle
    --adminuser={{ moodle_admin_username }}
    --adminpass={{ moodle_admin_password }}
    --adminemail={{ moodle_admin_email }}
    --lang=en
    --non-interactive
    --agree-license
  args:
    creates: /var/moodle/config.php
    chdir: "{{ moodle_root_path }}"

- name: Enable moodle ldap plugin 
  become: yes
  become_user: "{{ moodle_httpd_owner }}" 
  command: |
     moosh -p {{ moodle_root_path }} -n auth-manage enable ldap 
  args:

- name: Configure Moodle ldap 
  become: yes
  become_user: "{{ moodle_httpd_owner }}" 
  command: |
    moosh -p {{ moodle_root_path }} config-plugin-import /var/www/html/admin/files/auth_ldap_config.xml  

- name: Clear Moodle cache
  become: yes
  become_user: "{{ moodle_httpd_owner }}"
  command: |
     moosh -p {{ moodle_root_path }} cache-clear
  args:

- name: Copy moodle nginx configuration
  ansible.builtin.copy:
    src: nginx/moodle.local
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: '0644'

- name: Enable moodle nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/moodle.local
    dest: /etc/nginx/sites-enabled/moodle.local
    owner: root
    group: root
    state: link
  notify:
    - Restart Nginx

- name: setup cron job
  ansible.builtin.cron:
    name: moodle
    job: "/usr/bin/php {{ moodle_httpd_data_directory }}/moodle/admin/cli/cron.php >/dev/null"
    user: "{{ moodle_httpd_owner }}"
