---
# Installation moodle
    # quick install guide: https://docs.moodle.org/310/en/Installation_quick_guide
    # full install guide: https://docs.moodle.org/310/en/Installing_Moodle
    # Install PHP extensions -> moved to ospackages.yml

- name: Create and configure moodle database
  include_role:
    name: geerlingguy.mysql

- name: Create directory /var/moodlecontent
  ansible.builtin.file:
    path: /var/moodlecontent
    state: directory
    mode: '0755'

- name: Create directory /var/moodlesql
  ansible.builtin.file:
    path: /var/moodlesql
    state: directory
    mode: '0755'

- name: Clone moodle
  ansible.builtin.git:
    repo: https://github.com/moodle/moodle.git
    dest: /var/moodle
    version: MOODLE_310_STABLE
    force: yes
    depth: 1
    accept_hostkey: true

- name: Change owner and persmissions of directory /var/moodle
  ansible.builtin.file:
    path: /var/moodle
    state: directory
    owner: root
    mode: '0755'
    recurse: yes

- name: Create moodle data directory
  ansible.builtin.file:
    path: "{{ moodle_data_directory }}"
    state: directory
    owner: "{{ moodle_httpd_owner }}"
    group: "{{ moodle_httpd_group }}"
    mode: "{{ moodle_directory_mode }}"

- name: Configure moodle
  ansible.builtin.template:
    src: config.php.j2
    dest: "{{ moodle_httpd_data_directory }}/moodle/config.php"
    mode: "0755"

- name: Copy moodle nginx configuration
  ansible.builtin.copy:
    src: nginx/moodle.local
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: '0644'

- name: Enable moodle nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/moodle.local
    dest: /etc/nginx/sites-enabled/moodle.local
    owner: root
    group: root
    state: link
  notify:
    - Restart Nginx

- name: setup cron job
  ansible.builtin.cron:
    name: moodle
    job: "/usr/bin/php {{ moodle_httpd_data_directory }}/moodle/admin/cli/cron.php >/dev/null"
    user: "{{ moodle_httpd_owner }}"
