---
- name: Configure WPA 
  ansible.builtin.template:
    src: templates/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: "0400"

- name: Unblock Wifi
  ansible.builtin.shell: 
    cmd: rfkill unblock 0

- name: Configure hostapd
  ansible.builtin.template:
    src: templates/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf

- name: Register hostapd configuration
  ansible.builtin.template:
    src: templates/hostapd-init.j2
    dest: /etc/default/hostapd

- name: Configure udhcpd
  ansible.builtin.template:
    src: templates/udhcpd.conf.j2
    dest: /etc/udhcpd.conf

- name: Register udhcpd configuration
  ansible.builtin.template:
    src: templates/udhcpd-init.j2
    dest: /etc/default/udhcpd

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: "net.ipv4.ip_forward"
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: wlan0 up
  ansible.builtin.shell:
    cmd: ifconfig wlan0 10.11.0.1

- name: Enable and (re-)start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
    masked: no
  with_items:
    - udhcpd
    - hostapd

    # udhcpd wasn't starting properly at boot (probably starting before interface was ready)
    # for now we we just force it to restart after setting the interface
    #sudo("sh -c 'sed -i \"s/^exit 0//\" /etc/rc.local'", "Unable to remove exit from end of /etc/rc.local")
    #sudo("sh -c 'echo rfkill unblock all >> /etc/rc.local; echo ifconfig {} {} >> /etc/rc.local; echo service udhcpd restart >> /etc/rc.local;'".format(base_wifi, base_ip), "Unable to setup udhcpd reset at boot.")
    #sudo("sh -c 'echo exit 0 >> /etc/rc.local'", "Unable to replace exit to end of /etc/rc.local")
    # sudo("ifdown eth0 && ifdown wlan0 && ifup eth0 && ifup wlan0", "Unable to restart network interfaces.")
    #return True
    
 # there should be another solution for this.
- name: Fix udhcpd wasn't starting properly at boot
  ansible.builtin.copy:
    src:  rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: '0755' 
