- name: Copy the internet connection check script
  template:
    src: templates/check_internet_connection.sh.j2
    dest: /usr/local/bin/check_internet.sh
    owner: root
    group: root
    mode: '0744'    

- name: Add cron task to check internet connection
  ansible.builtin.cron:
    name: "check_internet"
    minute: "*"
    job: "/usr/local/bin/check_internet.sh"
    user: "root"
