---
# Fix for https://github.com/DEAN-ngo/elimupi/issues/137
# use DNS resolved and disable NetworkManager.

- name: Install systemd-resolved
  ansible.builtin.apt:
    name: systemd-resolved
    update_cache: yes
    state: present

- name: Disable NetworkManager service
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: no

- name: Run apt clean
  ansible.builtin.command: apt-get clean

- name: Reboot and running rc.local
  ansible.builtin.reboot:
    reboot_timeout: 1200
    post_reboot_delay: 60
