---
# creates a elimupi release file in /root/<release version>--date +%Y%m%d-%H%M

- name: create Elimupi release file
  ansible.builtin.file:
    path: "{{ elimupi_release_file }}" 
    state: touch

- name: Record rasbian image file in release file 
  ansible.builtin.shell: |
   echo  "Release:"  "{{ elimupi_release_file }}" | awk -F "/" '{print $1$3}' >>  "{{ elimupi_release_file }}"   
   echo "Raspberry Pi OS Distribution Release:" |  cat - /boot/issue.txt  >>  "{{ elimupi_release_file }}" 
   echo "Packages installed:"  >>  "{{ elimupi_release_file }}" 
   apt list --installed >>  "{{ elimupi_release_file }}"
  args:
    executable: /bin/bash

