- name: Enable ssh
  file:
    path: /boot/ssh
    state: touch

- name: Set hostname
  hostname:
    name: elimupi

- name: Set hostsfile
  copy:
    src: "hosts"
    dest: /etc/hosts

- name: Make content mount dir
  file:
    name: /mnt/content
    state: directory