# Put empty ssh bile on the boot partition (mounted under /boot on a Raspberry Pi)
- name: Enable ssh
  file:
    path: /boot/ssh
    state: touch

- name: Set hostname
  hostname:
    name: elimupi

- name: Set hostsfile
  copy:
    src: "hosts"
    dest: /etc/hosts

- name: Make content mount dir
  file:
    name: /mnt/content
    state: directory

- name: 'fstab-content'
  lineinfile:
    path: /etc/fstab
    regexp: '^LABEL=Content'
    line: 'LABEL=Content /mnt/content ntfs defaults,noatime,nofail 0 0'