---
- name: Configure WPA 
  ansible.builtin.template:
    src: templates/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: "0400"

- name: Configure hostapd
  ansible.builtin.template:
    src: templates/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf

- name: Register hostapd configuration
  ansible.builtin.template:
    src: templates/hostapd-init.j2
    dest: /etc/default/hostapd

- name: Configure dhcpcd
  ansible.builtin.template:
    src: templates/dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    
- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

 - name: Disable IPv6 with sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Copy rc.local
  ansible.builtin.copy:
    src: roles/common/files/rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: '0755'
   
 - name: Copy Wifi start script
  ansible.builtin.template:
    src: templates/wifistart.sh.j2
    dest: /usr/local/bin/wifistart.sh
    owner: root
    group: root
    mode: '0744'   

- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

- name: Enable and start rc-local.service
  systemd:
    name: rc-local
    state: started
    enabled: yes

# - name: Install iptables rules
#   template:
#     src: templates/rules.{{ item }}.j2
#     dest: /etc/iptables-rules.{{ item }}
#     owner: root
#     group: root
#     mode: '0744'
#   with_items:
#     - v4

# #- name: "Copy hs-iptables.service file"
#   ansible.builtin.template:
#     src: "hs-iptables.service.j2"
#     dest: "/etc/systemd/system/hs-iptables.service"
#     mode: "0744"

# - name: Reload systemd daemon
#   systemd:
#     daemon-reload: yes

# - name: Enable and start hs-iptables.service
#   systemd:
#     name: hs-iptables
#     state: started
#     enabled: yes

# - name: Enable services
#   ansible.builtin.systemd:
#     name: "{{ item }}"
#     enabled: yes
#     daemon_reload: yes
#     masked: no
#   with_items:
#     - dhcpcd
#     - hostapd