---
- name: Setup | Enable ssh
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: ssh

- name: Setup | Make .ssh dir for root user
  ansible.builtin.file:
    name: /root/.ssh
    state: directory
    mode: 0700

- name: "Setup | Add github key"
  copy:
    dest: "/root/.ssh/github_key"
    content: "{{ github_key }}"
    mode: 0600

- name: Setup | Copy ssh config for root user
  ansible.builtin.copy:
    src: "ssh_config"
    dest: "/root/.ssh/config"

- name: Setup | Add localhost hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1 .*'
    line: '127.0.0.1 localhost'

- name: Setup | Add VPN hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^10.254.252.1.*DEANVPN001.elimupi.dean'
    line: '10.254.252.1 DEANVPN001.elimupi.dean'

- name: Setup | Add web hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ host_ipv4_ipaddress }} {{ hosts_default_ipv4_hosts.hostnames | join(' ') }}"
    regexp: "^{{ host_ipv4_ipaddress }} .*"

- name: Install locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ system_locales }}"

- name: Setup | Make content mount dir
  ansible.builtin.file:
    name: /mnt/content
    state: directory

- name: Setup | Add /mnt/content to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^LABEL=Content'
    line: 'LABEL=Content /mnt/content ntfs defaults,noatime,nofail 0 0'

- name: Setup | Install devmon.service systemd unit file
  ansible.builtin.template:
    src: devmon.service.j2
    dest: /etc/systemd/system/devmon.service
    owner: root

- name: Setup | Enable devmon.service
  ansible.builtin.systemd:
    name: devmon.service
    state: started
    enabled: yes

- name:  Setup | Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Setup | Check if file /root/.resized exists
  ansible.builtin.stat:
    path: /root/.resized
  register: resized

- name: Setup | Resize root partition to maximum size
  block:
  - name: Setup | Change partition table
    ansible.builtin.shell:
      cmd: raspi-config nonint do_expand_rootfs >> /root/.resized
      creates: /root/.resized

  - name: Setup | Reboot after resizing root partition
    ansible.builtin.reboot:
      reboot_timeout: 1200
      post_reboot_delay: 60
    tags:
      - reboot
  when: not resized.stat.exists

# https://github.com/RPi-Distro/firmware-nonfree/blob/bullseye/debian/config/brcm80211/cypress/README.txt#L11-L13
- name: Setup | Install alternative firmware to maximise the number of clients in AP mode
  community.general.alternatives:
    name: cyfmac43455-sdio.bin
    path: /lib/firmware/cypress/cyfmac43455-sdio-minimal.bin
