---
# Install nginx site file
- name: Webserver | Copy configuration files
  ansible.builtin.copy:
    src: nginx/{{ item }}
    dest: /etc/nginx/sites-available/{{ item }}
  loop:
    - files.local
    - admin.local
  notify:
    - Restart Nginx

- name: Webserver | Enable websites
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  loop:
    - files.local
    - admin.local
  notify:
    - Restart Nginx

- name: Webserver | Create  directory /var/www/log
  ansible.builtin.file:
    path: /var/www/log
    state: directory
    mode: '0755'

- name: Webserver | Enable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - nginx

# Add Webinterface sudo settings
- name: Webserver | Set sudo file 020_elimupi
  ansible.builtin.copy:
    src: sudoers.d/020_elimupi
    dest: /etc/sudoers.d/020_elimupi   
    
# Add base groups -> moved to users.yml
# Create two deanadmin account for system -> moved to users.yml
# Create headmaster account for system -> moved to users.yml
# add Pi to teachers group -> moved to users.yml
   