---
# Install nginx site file
- name: Webserver | Copy configuration files
  ansible.builtin.copy:
    src: nginx/{{ item }}
    dest: /etc/nginx/sites-available/{{ item }}
  loop:
    - files.local
    - admin.local
    - elimupi.local
  notify:
    - Restart Nginx

- name: Webserver | Enable websites
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  loop:
    - files.local
    - admin.local
    - elimupi.local
  notify:
    - Restart Nginx

- name: Webserver | Remove default config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Webserver | Create  directory /var/www/log
  ansible.builtin.file:
    path: /var/www/log
    state: directory
    mode: '0755'

- name: Webserver | Enable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - nginx

- name: Set PHP upload_max_filesize 
  community.general.ini_file:
    path: "/etc/php/{{php_version}}/cli/php.ini"
    section: PHP
    option: upload_max_filesize
    value: 2G

- name: Set PHP FMP upload_max_filesize 
  community.general.ini_file:
    path: "/etc/php/{{php_version}}/cli/php.ini"
    section: PHP
    option: upload_max_filesize
    value: 2G

- name: Webserver | Clean /var/www/html
  ansible.builtin.file:
    state: absent
    path: /var/www/html

- name: Webserver | Checkout ElimuPi-Web-Interface
  ansible.builtin.git:
    repo: 'git@github-elimupi-web-interface:DEAN-ngo/ElimuPi-Web-Interface.git'
    dest:  /var/www/html
    version: main
    accept_hostkey: yes
  notify:
    - Restart Nginx

- name: Create directory /var/www/scripts
  ansible.builtin.file:
    path: /var/www/scripts
    state: directory
    mode: '0755'

- name: Webserver | Copy ElimuPi-Web-Interface admin scripts
  ansible.builtin.copy:
    src: /var/www/html/admin/scripts/{{ item }}
    dest: /var/www/scripts/{{ item }}
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  loop:
    - addstudent.sh
    - addteacher.sh
    - changepassword.sh
    - deleteuser.sh
    - restoreAccounts.sh

- name: Webserver | set server_names_hash_bucket_size
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regex: '^\s*#? *server_names_hash_bucket_size 64;'
    line: server_names_hash_bucket_size 64;

# Add Webinterface sudo settings
- name: Webserver | Set sudo file 020_elimupi
  ansible.builtin.copy:
    src: sudoers.d/020_elimupi
    dest: /etc/sudoers.d/020_elimupi   
