# install webserver / webinterface

# install package nginx -> moved to ospackages.yml
# install package php-fpm -> movd to ospackages.yml
    
# Install nginx site file
- name: Set admin.local
  copy:
    src: "nginx/admin.local"
    dest: /etc/nginx/sites-available/admin.local

- name: Set files.local
  copy:
    src: "nginx/files.local"
    dest: /etc/nginx/sites-available/files.local     

- name: Create a symbolic link admin.local
  ansible.builtin.file:
    src: /etc/nginx/sites-available/admin.local
    dest: /etc/nginx/sites-enabled/admin.local
    owner: pi
    group: pi
    state: link

- name: Create a symbolic link files.local
  ansible.builtin.file:
    src: /etc/nginx/sites-available/files.local
    dest: /etc/nginx/sites-enabled/files.local
    owner: pi
    group: pi
    state: link        
   
- name: Create  directory /var/www/log
  ansible.builtin.file:
    path: /var/www/log
    state: directory
    mode: '0755'
    
# restart NGINX service 
- name: Restart service nginx
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: nginx

# Add Webinterface sudo settings
- name: Set sudo file 020_elimupi
  copy:
    src: "sudoers.d/020_elimupi"
    dest: /etc/sudoers.d/sudoers.d/020_elimupi   
    
# Add base groups -> moved to users.yml
# Create two deanadmin account for system -> moved to users.yml
# Create headmaster account for system -> moved to users.yml
# add Pi to teachers group -> moved to users.yml
   