---
- name: Configure WPA
  ansible.builtin.template:
    src: templates/wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    mode: "0400"

- name: Configure network interfaces
  ansible.builtin.template:
    src: templates/interfaces.j2
    dest: /etc/network/interfaces
    mode: "0644"
    
- name: Configure resolvconf
  ansible.builtin.template:
    src: templates/resolv.head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
    
- name: Configure hostapd
  ansible.builtin.template:
    src: templates/hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf

- name: Register hostapd configuration
  ansible.builtin.template:
    src: templates/hostapd-init.j2
    dest: /etc/default/hostapd

- name: Unmask hostapd service
  systemd:
    name: hostapd
    masked: no

- name: Configure dhcpcd
  ansible.builtin.template:
    src: templates/dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf

#  https://forums.raspberrypi.com/viewtopic.php?t=360586
- name: Enable dhcpcd support on Bookworm
  ansible.builtin.file:
    src: /usr/share/dhcpcd/hooks/10-wpa_supplicant
    dest: /lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant
    owner: root
    group: root
    state: link

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable IPv6 with sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Copy rc.local
  ansible.builtin.copy:
    src: roles/common/files/rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: '0755'

- name: Copy Wifi start script
  ansible.builtin.template:
    src: templates/wifistart.sh.j2
    dest: /usr/local/bin/wifistart.sh
    owner: root
    group: root
    mode: '0744'

- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

- name: Enable and start rc-local.service
  systemd:
    name: rc-local
    state: started
    enabled: yes

- name: Unblock Wifi
  shell:
    cmd:  raspi-config nonint do_wifi_country '{{ host_country_code }}'
