---
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart OpenVPN
  ansible.builtin.service:
    name: openvpn@client
    state: restarted

- name: Restart netfilter-persistent
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted

- name: Reload systemd and restart dnsmasq
  block:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

