---
dependencies: []
galaxy_info:
  role_name: openldap
  author: Jan Michalek
  description: Ansible role for openldap server + ssl
  company: m-cloud.cz
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
