# Amicah-cyber
# Basic configuration

interface=wlan0
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

ssid=elimu
channel=8

# Hardware configuration
driver=nl80211

country_code=KE
# limit emissions to what is legal in country
ieee80211d=1
hw_mode=g

# Use WPA authentication
auth_algs=1
# Use WPA2
wpa=2
# Use a pre-shared key
wpa_key_mgmt=WPA-PSK
# The network passphrase
wpa_passphrase=1234567890
# Use AES, instead of TKIP
rsn_pairwise=CCMP
wmm_enabled=1
wpa_pairwise=CCMP