---
- name: 'Provision Image'
  hosts: all
  vars:
    template_path: templates/ # For local ansible runs, packer overwrites this.
  become: true

  tasks:
  - name: Enable ssh
    file:
      path: /boot/ssh
      state: touch

  - name: Set hostname
    hostname:
      name: elimupi

  - name: Set hostsfile
    template:
      src: "{{ template_path }}hosts"
      dest: /etc/hosts

  - name: Create groups
    group:
      name: "{{ item }}"
    loop:
      - admins
      - teachers
      - students

  - name: Change password
    user:
      name: pi
      password: "$6$b3gxvKWPUcs2g3t0$5XgHJvkpolByOwgowa3FZLF7Mp3g1u3fj7x/eoGlBRZ0IoauLx7Icik/lnaRcn7hJMnlwrdZwXNTZnUb.bXPN1" # elimupi
      group: pi
      groups:
      - teachers

  - name: Create admin account
    user:
      name: deanadmin
      password: "$6$8nyRab3gxvKWPUcs$tEoTxWLx8G6EusYnd0oldZrg9hcQj6YR4qjD.Alwr9B8HmyT23r1ERw4SyI6S./zhtcPcD2X8J.2slvVUsNHi." # topsecret
      group: admins

  - name: Create headmaster account
    user:
      name: headmaster
      password: "$6$JUefhA0qvD7b5LSh$6L5Pne1tpXvqL/VBu4U/pQh0K2XYuP6ip7I3XI0No.Q8AXLT1DY74F4gaAJ6vZ90jfg1O5IGA3jgaP.GyWqC8." # headmaster
      group: teachers

  - name: Upgrade OS
    apt:
      upgrade: dist

  # TODO update rbp firmware on first boot

  - name: Add repo key learningequality
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81

  - name: Add repository learningeqality
    apt_repository:
      repo: deb http://ppa.launchpad.net/learningequality/kolibri/ubuntu bionic main

  - name: Install applications
    apt:
      name:
      - ufw
      - git
      - nginx
      - php
      - php-fpm
      - php-curl
      - php-xml
      - php-mbstring
      - php-zip
      - php-gd
      - php-intl
      - php-xmlrpc
      - php-soap
      - php-mysql
      - iptables
      - libffi-dev
      - python3-pip
      - python3-pkg-resources
      - dirmngr
      - kolibri
      - kolibri-server
      - dnsmasq
      - citadel-suite
      - fdroidserver
      - usbmount
      - ntfs-3g
      - mariadb-server
      - hostapd
      - udhcpd

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
      autoclean: yes

  - name: Make content mount dir
    file:
      name: /mnt/content
      state: directory

  # TOFO fix firewall part
  # ==> arm-image.elimupi-raspios-buster: iptables/1.8.2 Failed to initialize nft: Protocol family not supported

  # - name: Reset firewall
  #   ufw:
  #     state: reset

  # - name: Enable firewall
  #   ufw:
  #     state: enabled
  #     policy: deny

  # - name: Allow http
  #   ufw:
  #     rule: allow
  #     port: 80
  #     proto: tcp
  #     src: '{{ item }}'
  #   loop:
  #     - fe80::/10
  #     - 10.0.0.0/8
  #     - 172.16.0.0/12
  #     - 192.168.0.0/16

  # - name: Allow ssh
  #   ufw:
  #     port: 22
  #     proto: tcp
  #     rule: allow
  #     src: '{{ item }}'
  #   loop:
  #     - fe80::/10
  #     - 10.0.0.0/8
  #     - 172.16.0.0/12
  #     - 192.168.0.0/16
