name: Packer

on:
  - push
  - workflow_dispatch

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies 
      run: sudo apt-get install kpartx qemu-user-static

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13.8'

    - name: Build plugin
      run: go install github.com/solo-io/packer-plugin-arm-image@master

    - name: Move plugin
      run: mv ~/go/bin/packer-plugin-arm-image .

    - name: Use latest Packer
      uses: hashicorp-contrib/setup-packer@v1

    - name: Validate template
      run: packer validate -syntax-only packer/image.pkr.hcl

    - name: Build image from template
      run: sudo packer build packer/image.pkr.hcl

    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        path: output.zip
